# Peripherals
CONFIG_GPIO=y
CONFIG_UART_CONSOLE=n
CONFIG_UART_MCUX_LPUART=n
CONFIG_UART_INTERRUPT_DRIVEN=n
CONFIG_CONSOLE=n
CONFIG_SERIAL=n

# Memory and execution
CONFIG_TRUSTED_EXECUTION_SECURE=n
CONFIG_CACHE=n
CONFIG_XIP=n
CONFIG_MP_MAX_NUM_CPUS=1
CONFIG_BT=n
CONFIG_FORCE_NO_ASSERT=y

# Code and algorithm
CONFIG_DEBUG=y

# Kernel
CONFIG_TIMESLICING=n
CONFIG_TICKLESS_KERNEL=y
CONFIG_SYS_CLOCK_TICKS_PER_SEC=100
CONFIG_EVENTS=y
CONFIG_NUM_PREEMPT_PRIORITIES=16
CONFIG_SCHED_MULTIQ=n


# Compiler and library
CONFIG_NEWLIB_LIBC=y
CONFIG_NEWLIB_LIBC_NANO=y
CONFIG_DEBUG_OPTIMIZATIONS=y

# Benchmark
CONFIG_BMTH_ENABLE=y
CONFIG_BMTH_FRDM_MCXN947=y
CONFIG_BENCHMARK_TEST_EVENT_TASK_SWITCH_BLOCK=y
